-- Create stage for embeddings
CREATE OR REPLACE STAGE AI_FEATURE_HUB.EMBEDDINGS_STAGE
    URL = 's3://REPLACE/embeddings'
    CREDENTIALS = (
        AWS_KEY_ID = 'REPLACE',
        AWS_SECRET_KEY = 'REPLACE'
    )
    FILE_FORMAT = (TYPE = JSON);

-- Create table to store embeddings snapshots
CREATE OR REPLACE TABLE AI_FEATURE_HUB.EMBEDDINGS_SNAPSHOT (
    SNAPSHOT_ID STRING PRIMARY KEY,
    OBJECT_PATH STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    METADATA VARIANT
);

-- Create a JSON file format with auto compression
CREATE OR REPLACE FILE FORMAT AI_FEATURE_HUB.JSON_COMPRESSED
    TYPE = JSON
    COMPRESSION = 'AUTO';

-- Create a Snowflake pipe for auto-ingest of embeddings
CREATE OR REPLACE PIPE AI_FEATURE_HUB.PIPE_LOAD_EMBEDDINGS
    AUTO_INGEST = TRUE
AS
    COPY INTO AI_FEATURE_HUB.EMBEDDINGS_SNAPSHOT (
        SNAPSHOT_ID,
        OBJECT_PATH,
        METADATA
    )
    FROM (
        SELECT 
            metadata$filename, 
            $1 
        FROM @AI_FEATURE_HUB.EMBEDDINGS_STAGE (FILE_FORMAT => 'AI_FEATURE_HUB.JSON_COMPRESSED')
    )
    ON_ERROR = 'CONTINUE';
