-- Task to trigger FAISS snapshot loader when new embeddings data is available
CREATE OR REPLACE TASK AI_FEATURE_HUB.TASK_FAISS_SNAPSHOT_LOADER
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = 'USING CRON 0 3 * * * UTC'
    WHEN SYSTEM$STREAM_HAS_DATA('AI_FEATURE_HUB.EMBEDDINGS_SNAPSHOT_STREAM')
AS
    CALL AI_FEATURE_HUB.TRIGGER_FAISS_INDEX_LOAD(
        (
            SELECT OBJECT_CONSTRUCT('s3', METADATA):s3_uri
            FROM AI_FEATURE_HUB.EMBEDDINGS_SNAPSHOT
            ORDER BY CREATED_AT DESC
            LIMIT 1
        )
    );
