-- run ingest and check views
CALL AI_FEATURE_HUB.INGEST_USAGE_TASK(200);
CALL AI_FEATURE_HUB.RUN_BILLING_RUN_ENHANCED(DATEADD('day',-1,CURRENT_TIMESTAMP())::STRING,CURRENT_TIMESTAMP()::STRING,NULL,TRUE);
SELECT COUNT(*) FROM AI_FEATURE_HUB.TENANT_FEATURE_USAGE;
SELECT COUNT(*) FROM AI_FEATURE_HUB.BILLING_LINE_ITEM;