#!/bin/bash
set -e
snowsql -a $SNOW_ACCOUNT -u $SNOW_USER -r $SNOW_ROLE -w $SNOW_WAREHOUSE -d $SNOW_DB -s $SNOW_SCHEMA -q "ALTER TASK AI_FEATURE_HUB.TASK_INGEST_USAGE RESUME;ALTER TASK AI_FEATURE_HUB.TASK_PERSIST_BILLING RESUME;ALTER TASK AI_FEATURE_HUB.TASK_DAILY_RECONCILE RESUME;ALTER TASK AI_FEATURE_HUB.TASK_REFRESH_BILLING_MVS RESUME;ALTER TASK AI_FEATURE_HUB.TASK_CHECK_MODEL_P95 RESUME;"