-- PUT file://sql/ops/300_next_005_log_model_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.LOG_MODEL(req VARIANT) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300_next_005_log_model_min.py') HANDLER='log_model';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.LOG_MODEL TO ROLE YOUR_RUN_ROLE;