-- PUT file://sql/ops/300_next_002_emit_alert_min.py @~/ AUTO_COMPRESS=FALSE;

CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.EMIT_ALERT(
    NAME STRING, 
    DETAILS VARIANT, 
    LEVEL STRING
)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.10'
IMPORTS = ('@~/300_next_002_emit_alert_min.py')
HANDLER = 'emit_alert';

GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.EMIT_ALERT(STRING, VARIANT, STRING) TO ROLE YOUR_RUN_ROLE;