-- PUT file://sql/ops/300_next_003_run_billing_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.RUN_BILLING(run_start STRING,run_end STRING,preview BOOLEAN DEFAULT TRUE) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300_next_003_run_billing_min.py') HANDLER='run_billing';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.RUN_BILLING TO ROLE YOUR_RUN_ROLE;