-- PUT file://sql/ops/300b_009_check_pipes_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.CHECK_PIPES_AND_LOAD_METRICS() RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300b_009_check_pipes_min.py') HANDLER='check_pipes';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.CHECK_PIPES_AND_LOAD_METRICS TO ROLE YOUR_RUN_ROLE;