-- PUT file://sql/ops/300b_004_run_billing_wrapper_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.RUN_BILLING_WRAPPER(payload VARIANT) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300b_004_run_billing_wrapper_min.py') HANDLER='handler';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.RUN_BILLING_WRAPPER TO ROLE YOUR_RUN_ROLE;