-- PUT file://sql/ops/300c_012_verify_ingest_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.VERIFY_INGEST() RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300c_012_verify_ingest_min.py') HANDLER='check';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.VERIFY_INGEST TO ROLE YOUR_RUN_ROLE;