-- PUT file://sql/ops/300d_014_promote_model_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.PROMOTE_MODEL(model_id STRING) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300d_014_promote_model_min.py') HANDLER='promote_model';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.PROMOTE_MODEL TO ROLE YOUR_RUN_ROLE;