-- PUT file://sql/ops/300d_003_jobrun_writer_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.WRITE_JOBRUN(name STRING,status STRING,details VARIANT) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300d_003_jobrun_writer_min.py') HANDLER='write_jobrun';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.WRITE_JOBRUN TO ROLE YOUR_RUN_ROLE;