-- PUT file://sql/ops/300d_011_register_model_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.REGISTER_MODEL(model_key STRING,version STRING,meta VARIANT) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300d_011_register_model_min.py') HANDLER='register_model';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.REGISTER_MODEL TO ROLE YOUR_RUN_ROLE;