-- PUT file://sql/ops/300e_005_invoice_notification_wrapper_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.NOTIFY_INVOICE(invoice_id STRING,summary STRING) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300e_005_invoice_notification_wrapper_min.py') HANDLER='notify';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.NOTIFY_INVOICE TO ROLE YOUR_RUN_ROLE;