-- PUT file://sql/ops/300e_007_billing_reconciliation_job_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.RUN_BILLING_RECONCILE() RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300e_007_billing_reconciliation_job_min.py') HANDLER='billing_reconcile';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.RUN_BILLING_RECONCILE TO ROLE YOUR_RUN_ROLE;