-- PUT file://sql/ops/300h_013_run_apply_rate_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.RUN_APPLY_RATE_WRAPPER(billing_date STRING) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300h_013_run_apply_rate_min.py') HANDLER='run_apply_rate';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.RUN_APPLY_RATE_WRAPPER TO ROLE YOUR_RUN_ROLE;