-- PUT file://sql/ops/300h_002_ingest_raw_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.INGEST_RAW(payload VARIANT) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300h_002_ingest_raw_min.py') HANDLER='ingest_raw';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.INGEST_RAW TO ROLE YOUR_RUN_ROLE;