-- PUT file://sql/ops/300h_006_usage_upsert_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.UPSERT_USAGE(usage VARIANT) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/300h_006_usage_upsert_min.py') HANDLER='upsert_usage';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.UPSERT_USAGE TO ROLE YOUR_RUN_ROLE;