CREATE OR REPLACE API_INTEGRATION AI_FEATURE_HUB.ANN_API_INT TYPE=EXTERNAL_OAUTH ENABLED=true API_PROVIDER='aws_apigateway' API_AWS_ROLE_ARN='arn:aws:iam::REPLACE:role/REPLACE' SECRETS='"{}"';
CREATE OR REPLACE API_INTEGRATION AI_FEATURE_HUB.SNOWFLAKE_NATIVE_APP TYPE=EXTERNAL_OAUTH ENABLED=true;
-- External Function registration template (modify URL/auth per deployment)
CREATE OR REPLACE EXTERNAL FUNCTION AI_FEATURE_HUB.SIMILARITY_QUERY(query VARIANT)
RETURNS VARIANT
API_INTEGRATION = AI_FEATURE_HUB.ANN_API_INT
HEADERS = ( 'Content-Type'='application/json' )
MAX_BATCH_ROWS=100
AS 'https://REPLACE-API-GW/ann_search';
