-- register_submit_approve.sql
-- PUT file://sql/billing/submit_and_approve_procs.py @~/ AUTO_COMPRESS=FALSE;

CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.SUBMIT_RATE_RULE_TO_STAGING(staging_json STRING)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.10'
IMPORTS = ('@~/submit_and_approve_procs.py')
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'submit_rate_rule';

CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.APPROVE_RATE_RULE(staging_id STRING, approver STRING)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.10'
IMPORTS = ('@~/submit_and_approve_procs.py')
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'approve_rate_rule';

CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.REJECT_RATE_RULE(staging_id STRING, approver STRING, reason STRING)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.10'
IMPORTS = ('@~/submit_and_approve_procs.py')
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'reject_rate_rule';

GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.SUBMIT_RATE_RULE_TO_STAGING TO ROLE YOUR_STREAMLIT_ROLE;
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.APPROVE_RATE_RULE TO ROLE YOUR_APPROVER_ROLE;
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.REJECT_RATE_RULE TO ROLE YOUR_APPROVER_ROLE;
