-- PUT file://sql/billing/retry_failed_payments_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.PROCESS_PAYMENT_FOR_FAILED() RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/retry_failed_payments_min.py') HANDLER='process_payment_for_failed';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.PROCESS_PAYMENT_FOR_FAILED TO ROLE YOUR_RUN_ROLE;