-- PUT file://sql/billing/process_payment_stream_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.PROCESS_PAYMENT_STREAM() RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/process_payment_stream_min.py') HANDLER='process_payment_stream';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.PROCESS_PAYMENT_STREAM TO ROLE YOUR_RUN_ROLE;