-- PUT file://sql/ops/create_retention_proc_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.SCHEDULE_RETENTION_JOB(policy_id STRING) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/create_retention_proc_min.py') HANDLER='schedule_retention_job';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.SCHEDULE_RETENTION_JOB TO ROLE YOUR_RUN_ROLE;