-- PUT ingest python first: PUT file://sql/ingest/ingest_usage_sp_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.INGEST_USAGE_TASK(limit NUMBER DEFAULT 1000) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/ingest_usage_sp_min.py') HANDLER='ingest_usage_task';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.INGEST_USAGE_TASK TO ROLE YOUR_RUN_ROLE;