-- PUT file://sql/billing/apply_adjustment_min.py @~/ AUTO_COMPRESS=FALSE;
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.APPLY_ADJUSTMENT(invoice_id STRING, amount FLOAT, reason STRING) RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION='3.10' IMPORTS=('@~/apply_adjustment_min.py') HANDLER='apply_adjustment';
GRANT EXECUTE ON PROCEDURE AI_FEATURE_HUB.APPLY_ADJUSTMENT TO ROLE YOUR_RUN_ROLE;