CREATE OR REPLACE TABLE AI_FEATURE_HUB.RATE_CARD(
    RATE_ID STRING PRIMARY KEY,
    FEATURE_KEY STRING,
    BASE_UNIT_PRICE NUMBER,
    CURRENCY STRING,
    VALID_FROM DATE,
    VALID_TO DATE
);
GRANT SELECT, INSERT ON AI_FEATURE_HUB.RATE_CARD TO ROLE YOUR_RUN_ROLE;