CREATE OR REPLACE VIEW AI_FEATURE_HUB.V_RATECARD_CURRENT AS
SELECT *
FROM AI_FEATURE_HUB.RATE_CARD
WHERE effective_date <= CURRENT_DATE()
QUALIFY ROW_NUMBER() OVER (PARTITION BY feature_key ORDER BY effective_date DESC) = 1;