-- Use the target database and schema
USE DATABASE AI_PLATFORM;
USE SCHEMA AI_FEATURE_HUB;

-- Create RATE_RULES table
CREATE OR REPLACE TABLE AI_FEATURE_HUB.RATE_RULES (
    RULE_ID STRING PRIMARY KEY,
    FEATURE_KEY STRING,
    RULE_TYPE STRING,
    CONFIG VARIANT,
    PRIORITY NUMBER,
    EFFECTIVE_FROM TIMESTAMP_LTZ,
    EFFECTIVE_TO TIMESTAMP_LTZ,
    ACTIVE BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create RATE_RULES_STAGING table
CREATE OR REPLACE TABLE AI_FEATURE_HUB.RATE_RULES_STAGING (
    STAGING_ID STRING PRIMARY KEY,
    FEATURE_KEY STRING,
    RULE_TYPE STRING,
    CONFIG VARIANT,
    PRIORITY NUMBER DEFAULT 100,
    SUBMITTED_BY STRING,
    SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    APPROVED BOOLEAN DEFAULT FALSE,
    APPROVED_BY STRING,
    APPROVED_AT TIMESTAMP_LTZ,
    REJECTED BOOLEAN DEFAULT FALSE,
    REJECT_REASON STRING,
    ARCHIVED BOOLEAN DEFAULT FALSE
);

-- Create RATE_RULES_APPROVAL_AUDIT table
CREATE OR REPLACE TABLE AI_FEATURE_HUB.RATE_RULES_APPROVAL_AUDIT (
    AUDIT_ID STRING PRIMARY KEY,
    STAGING_ID STRING,
    ACTION STRING,
    ACTOR STRING,
    ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    DETAILS VARIANT
);
