-- Table to track billing preview runs
CREATE OR REPLACE TABLE AI_FEATURE_HUB.PREVIEW_AUDIT (
    PREVIEW_ID STRING PRIMARY KEY,
    INVOICE_HASH STRING,
    ACCOUNT_ID STRING,
    PREVIEW_JSON VARIANT,
    PREVIEW_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Table to track persisted billing runs
CREATE OR REPLACE TABLE AI_FEATURE_HUB.BILLING_RUN_AUDIT (
    RUN_ID STRING PRIMARY KEY,
    INVOICE_HASH STRING,
    ACCOUNT_ID STRING,
    PAYLOAD VARIANT,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
