CREATE OR REPLACE VIEW AI_FEATURE_HUB.V_ACTIVE_RATE_RULES_FULL AS
SELECT 
    r.RULE_ID,
    r.FEATURE_KEY,
    r.RULE_TYPE,
    r.CONFIG,
    r.PRIORITY,
    r.EFFECTIVE_FROM,
    r.EFFECTIVE_TO,
    r.ACTIVE,
    s.STAGING_ID,
    s.SUBMITTED_BY,
    s.SUBMITTED_AT
FROM 
    AI_FEATURE_HUB.RATE_RULES r
LEFT JOIN 
    AI_FEATURE_HUB.RATE_RULES_STAGING s 
    ON r.RULE_ID = s.STAGING_ID
WHERE 
    r.ACTIVE = TRUE;
