-- Schedule a daily reconciliation task
CREATE OR REPLACE TASK AI_FEATURE_HUB.TASK_DAILY_RECONCILE
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
    CALL AI_FEATURE_HUB.RECONCILE_BILLING_VS_USAGE(NULL, NULL, NULL);
