CREATE OR REPLACE TASK AI_FEATURE_HUB.TASK_COMPUTE_INVOICE_HASH WAREHOUSE='COMPUTE_WH' SCHEDULE='USING CRON 0 3 * * * UTC' AS CALL AI_FEATURE_HUB.COMPUTE_INVOICE_HASH((SELECT invoice_id FROM AI_FEATURE_HUB.SUBSCRIPTION_INVOICES WHERE invoice_hash IS NULL LIMIT 1));

