-- Procedure to refresh all materialized views
CREATE OR REPLACE PROCEDURE AI_FEATURE_HUB.REFRESH_ALL_MV()
    RETURNS STRING
    LANGUAGE SQL
AS
$$
BEGIN
    REFRESH MATERIALIZED VIEW AI_FEATURE_HUB.MV_BILLING_MONTHLY;
    REFRESH MATERIALIZED VIEW AI_FEATURE_HUB.MV_SOME_OTHER;
    
    RETURN 'ok';
END;
$$;

-- Task to schedule refreshing of materialized views
CREATE OR REPLACE TASK AI_FEATURE_HUB.TASK_REFRESH_MVS
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = 'USING CRON 30 2 * * * UTC'
AS
    CALL AI_FEATURE_HUB.REFRESH_ALL_MV();
