CREATE OR REPLACE TASK AI_FEATURE_HUB.TASK_RECONCILIATION_ALERTS
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = 'USING CRON 0 * * * * UTC' -- hourly
AS
CALL AI_FEATURE_HUB.CHECK_RECONCILIATION_ISSUES_AND_ALERT();